ddpm :
  model :
    noise_steps : 500
    beta_start : 0.0001
    beta_end : 0.02
    img_size : 32
    in_channels : 3
    out_channels : 3
    time_dim : 256
  train :
    batch_size : 64
    nb_epochs : 20
    learning_rate : 0.0002