ddpm :
  model :
    noise_steps : 300
    beta_start : 0.0001
    beta_end : 0.02
    img_size : 32
    in_channels : 3
    out_channels : 3
    time_dim : 32
  train :
    batch_size : 128
    nb_epochs : 10
    learning_rate : 0.0001