ddpm :
  # Model hyperparameters
  noise_steps : 500 # 1000 in original paper
  beta_start : 0.0001
  beta_end : 0.02
  img_size : 32
  img_channels : 3 # 3
  time_dim : 128 # 256 in original paper
  # Train hyperparameters
  batch_size : 128 # 16
  nb_epochs : 100
  learning_rate : 0.0003 # works with 0.0003

gan :
  # Model hyperparameters
  img_size : 32
  img_channels : 3
  latent_dim : 128
  weight_clip : 0.01
  nb_critic_itr : 5
  lambda_recon : 10
  # Train hyperparameters
  batch_size : 128
  nb_epochs : 50
  learning_rate : 0.0003