data_dir : "data"
log_dir : "logs"
weight_dir : "weights"
model_dir : "models"
dataset_dir : "datasets"
train_dir : "runs"
config_dir : "configs"
base_ddpm_name : "base_ddpm_v0"
base_gan_name : "base_wgan_v0"
outpainting_ddpm_name : "inpainting_ddpm_v0"
outpainting_gan_name : "inpainting_gan_v0"