data_dir : "data"
log_dir : "logs"
weight_dir : "weights"
model_dir : "models"
dataset_dir : "datasets"
train_dir : "runs/train"
test_dir : "runs/test"
config_dir : "configs"
visualization_dir : "samples"
base_gan_name : "base_gan_v0"
base_ddpm_name : "base_ddpm_v0"
inpainting_gan_name : "inpainting_gan_v0"
inpainting_ddpm_name : "inpainting_ddpm_v0"
outpainting_gan_name : "outpainting_gan_v0"
outpainting_ddpm_name : "outpainting_ddpm_v0"