data_dir : "data"
log_dir : "logs"
weight_dir : "weights"
model_dir : "models"
dataset_dir : "datasets"
train_dir : "runs"
config_dir : "configs"
output_real_dir : "real_imgs"
output_gen_dir : "gen_imgs"
output_mask_dir : "mask_imgs"
base_ddpm_name : "base_ddpm_v0"
base_gan_name : "base_wgan_v0"
inpainting_ddpm_name : "inpainting_ddpm"
inpainting_wgan_name : "inpainting_wgan"
upsampling_ddpm_name : "upsampling_ddpm"
upsampling_wgan_name : "upsampling_wgan"
outpainting_ddpm_name : "outpainting_ddpm"
outpainting_wgan_name : "outpainting_wgan"
denoising_ddpm_name : "denoising_ddpm"
denoising_wgan_name : "denoising_wgan"