data_dir : "data"
log_dir : "logs"
weight_dir : "weights"
dataset_dir : "datasets"
train_dir : "runs"
config_dir : "configs"
output_real_dir : "real_imgs"
output_gen_dir : "gen_imgs"
output_mask_dir : "mask_imgs"
inpainting_ddpm_name : "inpainting_ddpm"
inpainting_wgan_name : "inpainting_wgan"
